baseURL: http://example.org/
languageCode: en-us
title: "2022 Congressional Midterm Elections Forecast"
theme: hugo-ink
paginate: 5
copyright: © Kento Yamada
pygmentsstyle: vs
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
googleAnalytics: UA-123-45
disqusShortname: ink-demo
params:
  disableDisqusTypes: page
  featherIconsCDN: yes
  mode: auto
  social:
    - icon: github
      name: Github
      url: https://github.com/kentoyamada100/election-analytics-2022-midterms
  subtitle: "Kento Yamada (Harvard College) | Gov 1347: Election Analytics"
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Posts
      url: /posts
      weight: 2
    - name: About
      url: /about
      weight: 3
taxonomies:
  tag: tags
